sudo: required
services: 
    -docker

before-install:
    - docker build -t zukdeividas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true zukdeividas/react-test npm test

after_success:
    - docker build -t zukdeividas/multi-client ./client
    - docker build -t zukdeividas/multi-nginx ./nginx
    - docker build -t zukdeividas/multi-server ./server
    - docker build -t zukdeividas/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push zukdeividas/multi-client
    - docker push zukdeividas/multi-nginx
    - docker push zukdeividas/multi-server
    - docker push zukdeividas/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-797373521527
    bucket_path: multi-docker
    
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY